server:
  applicationConnectors:
  - type: http
    port: 9813
logging:
  level: DEBUG
  appenders:
      - type: file
        currentLogFilename: D:/log.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: D:/loga-%d.log
        archivedFileCount: 5
        timeZone: UTC